### ISSUE TITLE
Stuck at "One moment please...connecting your call..."

### ISSUE THREAD

**Issue by yepher** [buildar/getting_started_with_webrtc#1]
I am reading through the book "Getting Started with WebRTC". 

I installed node.js and websockets. I am running "node webrtc_signal_server.js".

If I open two tabs in chrome and hit "http://192.168.200.209:1234/#1390508125279-5240" it works just fine. But I I do the same test from two machines both browsers say "One moment please...connecting your call...".

This is what I see in the Chrome browsers javascript console:

```
setting up local video stream (index):368
setting up connection to signaling server (index):148
you are the Callee (index):180
updating UI to loading_state (index):209
sending 'join' signal for call token:#1390508677469-5908 (index):190
sending 'callee_arrived' signal for call token:#1390508677469-5908 (index):199
new local stream added (index):376
local stream added to peer_connection to send to remote peer 
```

Any idea what might be going wrong?

**Comment by AnushaTeleparadigm** [comment]
If i use localhost it is working fine but if i use my ip address it is struck at One moment please...connecting your call.
